import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';
import { Insight, Agent, AgentType, AgentFrequency } from '@/types';
import { useAuth } from '@/contexts/AuthContext';
import {
  useDocuments as useDocumentsQuery,
  useAddDocument,
  useRemoveDocument,
  useAgents as useAgentsQuery,
  useAddAgent,
  useUpdateAgent,
  useDeleteAgent,
  useInsights as useInsightsQuery,
  useAddInsight,
  StoredDocument,
} from '@/hooks/useSupabaseData';

interface DocumentsContextType {
  // Documents
  documents: StoredDocument[];
  addDocument: (doc: Omit<StoredDocument, 'id' | 'uploadedAt'>) => Promise<StoredDocument>;
  addDocuments: (docs: Omit<StoredDocument, 'id' | 'uploadedAt'>[]) => Promise<StoredDocument[]>;
  removeDocument: (id: string) => void;
  hasDocuments: boolean;
  isLoading: boolean;
  
  // Agents
  agents: Agent[];
  addAgent: (agent: Omit<Agent, 'id' | 'createdAt' | 'updatedAt' | 'outputCount' | 'status' | 'isPreset'>) => Promise<Agent>;
  updateAgent: (id: string, updates: Partial<Omit<Agent, 'id' | 'createdAt' | 'isPreset'>>) => void;
  deleteAgent: (id: string) => void;
  hasAgents: boolean;
  customAgents: Agent[];
  presetAgents: Agent[];
  
  // Insights (generated by agents)
  generatedInsights: Insight[];
  addInsight: (insight: Omit<Insight, 'id'>) => Promise<Insight>;
  
  // First-time user flow
  showFirstDocumentModal: boolean;
  setShowFirstDocumentModal: (show: boolean) => void;
  isFirstDocument: boolean;
  
  // Upload modal control
  showUploadModal: boolean;
  setShowUploadModal: (show: boolean) => void;
  uploadModalSource: string;
  openUploadModal: (source: string) => void;
}

const DocumentsContext = createContext<DocumentsContextType | undefined>(undefined);

export function DocumentsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  
  // Supabase queries
  const { data: documents = [], isLoading: docsLoading } = useDocumentsQuery();
  const { data: agents = [], isLoading: agentsLoading } = useAgentsQuery();
  const { data: generatedInsights = [], isLoading: insightsLoading } = useInsightsQuery();
  
  // Mutations
  const addDocumentMutation = useAddDocument();
  const removeDocumentMutation = useRemoveDocument();
  const addAgentMutation = useAddAgent();
  const updateAgentMutation = useUpdateAgent();
  const deleteAgentMutation = useDeleteAgent();
  const addInsightMutation = useAddInsight();
  
  // Local UI state (not persisted)
  const [showFirstDocumentModal, setShowFirstDocumentModal] = useState(false);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [uploadModalSource, setUploadModalSource] = useState('');
  const [isFirstDocument, setIsFirstDocument] = useState(true);

  const isLoading = docsLoading || agentsLoading || insightsLoading;

  // Use only real DB agents, no mocks
  const allAgents = React.useMemo(() => {
    return agents || [];
  }, [agents]);

  const addDocument = useCallback(async (doc: Omit<StoredDocument, 'id' | 'uploadedAt'>): Promise<StoredDocument> => {
    const result = await addDocumentMutation.mutateAsync(doc);
    
    // Show first document modal if this was the first document
    if (documents.length === 0 && isFirstDocument) {
      setIsFirstDocument(false);
      setShowFirstDocumentModal(true);
    }
    
    return {
      id: result.id,
      name: result.title || doc.name,
      type: result.source_type || doc.type,
      source: doc.source,
      uploadedAt: new Date(result.created_at || Date.now()),
      aiTitle: result.title,
      contentText: result.content,
    };
  }, [addDocumentMutation, documents.length, isFirstDocument]);

  const addDocuments = useCallback(async (docs: Omit<StoredDocument, 'id' | 'uploadedAt'>[]): Promise<StoredDocument[]> => {
    const results: StoredDocument[] = [];
    for (const doc of docs) {
      const result = await addDocument(doc);
      results.push(result);
    }
    return results;
  }, [addDocument]);

  const removeDocument = useCallback((id: string) => {
    removeDocumentMutation.mutate(id);
  }, [removeDocumentMutation]);

  const addAgentHandler = useCallback(async (agentData: Omit<Agent, 'id' | 'createdAt' | 'updatedAt' | 'outputCount' | 'status' | 'isPreset'>): Promise<Agent> => {
    const result = await addAgentMutation.mutateAsync(agentData);
    
    return {
      ...agentData,
      id: result.id,
      createdAt: new Date(result.created_at),
      updatedAt: new Date(result.updated_at),
      outputCount: 0,
      status: 'active',
      isPreset: false,
    };
  }, [addAgentMutation]);

  const updateAgentHandler = useCallback((id: string, updates: Partial<Omit<Agent, 'id' | 'createdAt' | 'isPreset'>>) => {
    updateAgentMutation.mutate({ id, updates });
  }, [updateAgentMutation]);

  const deleteAgentHandler = useCallback((id: string) => {
    const agent = allAgents.find(a => a.id === id);
    if (agent?.isPreset) return; // Don't delete preset agents
    deleteAgentMutation.mutate(id);
  }, [deleteAgentMutation, allAgents]);

  const addInsightHandler = useCallback(async (insight: Omit<Insight, 'id'>): Promise<Insight> => {
    const result = await addInsightMutation.mutateAsync(insight);
    return {
      ...insight,
      id: result.id,
    };
  }, [addInsightMutation]);

  const openUploadModal = useCallback((source: string) => {
    setUploadModalSource(source);
    setShowUploadModal(true);
  }, []);

  // Derived values
  const customAgents = allAgents.filter(a => !a.isPreset);
  const presetAgents = allAgents.filter(a => a.isPreset);

  const value: DocumentsContextType = {
    documents,
    addDocument,
    addDocuments,
    removeDocument,
    hasDocuments: documents.length > 0,
    isLoading,
    agents: allAgents,
    addAgent: addAgentHandler,
    updateAgent: updateAgentHandler,
    deleteAgent: deleteAgentHandler,
    hasAgents: allAgents.length > 0,
    customAgents,
    presetAgents,
    generatedInsights,
    addInsight: addInsightHandler,
    showFirstDocumentModal,
    setShowFirstDocumentModal,
    isFirstDocument,
    showUploadModal,
    setShowUploadModal,
    uploadModalSource,
    openUploadModal,
  };

  return (
    <DocumentsContext.Provider value={value}>
      {children}
    </DocumentsContext.Provider>
  );
}

export function useDocuments() {
  const context = useContext(DocumentsContext);
  if (context === undefined) {
    throw new Error('useDocuments must be used within a DocumentsProvider');
  }
  return context;
}

// Re-export types for convenience
export type { StoredDocument } from '@/hooks/useSupabaseData';
