import React, { createContext, useContext, useState, useCallback, useEffect, ReactNode } from 'react';
import { Insight, Agent, AgentType, AgentFrequency } from '@/types';
import { mockAgents } from '@/data/mockData';

// localStorage keys
const STORAGE_KEYS = {
  documents: 'insidepod_documents',
  agents: 'insidepod_agents',
  insights: 'insidepod_insights',
  hasSeenFirstDocumentModal: 'insidepod_has_seen_first_doc_modal',
};

// Document type stored in context
export interface StoredDocument {
  id: string;
  name: string;
  type: string;
  size?: number;
  source: 'upload' | 'connected';
  sourceLabel?: string;
  uploadedAt: Date;
  aiTitle?: string;
  contentText?: string; // Parsed content or placeholder
}

// Helper functions for localStorage
function loadFromStorage<T>(key: string, defaultValue: T): T {
  try {
    const stored = localStorage.getItem(key);
    if (stored) {
      const parsed = JSON.parse(stored);
      return parsed;
    }
  } catch (e) {
    console.warn(`Failed to load ${key} from localStorage:`, e);
  }
  return defaultValue;
}

function saveToStorage<T>(key: string, value: T): void {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.warn(`Failed to save ${key} to localStorage:`, e);
  }
}

// Hydrate dates from JSON (converts ISO strings back to Date objects)
function hydrateDates<T>(obj: T, dateFields: string[]): T {
  if (Array.isArray(obj)) {
    return obj.map(item => hydrateDates(item, dateFields)) as T;
  }
  if (obj && typeof obj === 'object') {
    const hydrated = { ...obj } as any;
    for (const field of dateFields) {
      if (hydrated[field] && typeof hydrated[field] === 'string') {
        hydrated[field] = new Date(hydrated[field]);
      }
    }
    return hydrated;
  }
  return obj;
}

interface DocumentsContextType {
  // Documents
  documents: StoredDocument[];
  addDocument: (doc: Omit<StoredDocument, 'id' | 'uploadedAt'>) => StoredDocument;
  addDocuments: (docs: Omit<StoredDocument, 'id' | 'uploadedAt'>[]) => StoredDocument[];
  removeDocument: (id: string) => void;
  hasDocuments: boolean;
  
  // Agents
  agents: Agent[];
  addAgent: (agent: Omit<Agent, 'id' | 'createdAt' | 'updatedAt' | 'outputCount' | 'status' | 'isPreset'>) => Agent;
  updateAgent: (id: string, updates: Partial<Omit<Agent, 'id' | 'createdAt' | 'isPreset'>>) => void;
  deleteAgent: (id: string) => void;
  hasAgents: boolean;
  customAgents: Agent[];
  presetAgents: Agent[];
  
  // Insights (generated by agents)
  generatedInsights: Insight[];
  addInsight: (insight: Omit<Insight, 'id'>) => Insight;
  
  
  // First-time user flow
  showFirstDocumentModal: boolean;
  setShowFirstDocumentModal: (show: boolean) => void;
  isFirstDocument: boolean;
  
  // Upload modal control
  showUploadModal: boolean;
  setShowUploadModal: (show: boolean) => void;
  uploadModalSource: string;
  openUploadModal: (source: string) => void;
}

const DocumentsContext = createContext<DocumentsContextType | undefined>(undefined);

// Initialize agents: merge stored custom agents with preset agents
function initializeAgents(): Agent[] {
  const storedAgents = loadFromStorage<Agent[]>(STORAGE_KEYS.agents, []);
  const hydratedStoredAgents = hydrateDates(storedAgents, ['createdAt', 'updatedAt', 'lastRun', 'nextRun']);
  
  // Get custom agents from storage (non-preset)
  const customAgents = hydratedStoredAgents.filter(a => !a.isPreset);
  
  // Get preset agents from storage (to preserve any updates) or fallback to mock
  const storedPresetAgents = hydratedStoredAgents.filter(a => a.isPreset);
  
  // If we have stored preset agents, use them; otherwise use mock
  const presetAgents = storedPresetAgents.length > 0 ? storedPresetAgents : mockAgents;
  
  return [...customAgents, ...presetAgents];
}

// Initialize documents from storage
function initializeDocuments(): StoredDocument[] {
  const stored = loadFromStorage<StoredDocument[]>(STORAGE_KEYS.documents, []);
  return hydrateDates(stored, ['uploadedAt']);
}

// Initialize insights from storage
function initializeInsights(): Insight[] {
  const stored = loadFromStorage<Insight[]>(STORAGE_KEYS.insights, []);
  return hydrateDates(stored, ['timestamp']);
}


export function DocumentsProvider({ children }: { children: ReactNode }) {
  // Initialize state from localStorage
  const [documents, setDocuments] = useState<StoredDocument[]>(initializeDocuments);
  const [agents, setAgents] = useState<Agent[]>(initializeAgents);
  const [generatedInsights, setGeneratedInsights] = useState<Insight[]>(initializeInsights);
  const [showFirstDocumentModal, setShowFirstDocumentModal] = useState(false);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [uploadModalSource, setUploadModalSource] = useState('');
  
  // Check if user has seen first document modal before
  const [isFirstDocument, setIsFirstDocument] = useState(() => {
    const hasSeenModal = loadFromStorage<boolean>(STORAGE_KEYS.hasSeenFirstDocumentModal, false);
    const hasStoredDocs = loadFromStorage<StoredDocument[]>(STORAGE_KEYS.documents, []).length > 0;
    return !hasSeenModal && !hasStoredDocs;
  });

  // Persist documents to localStorage
  useEffect(() => {
    saveToStorage(STORAGE_KEYS.documents, documents);
  }, [documents]);

  // Persist agents to localStorage
  useEffect(() => {
    saveToStorage(STORAGE_KEYS.agents, agents);
  }, [agents]);

  // Persist insights to localStorage
  useEffect(() => {
    saveToStorage(STORAGE_KEYS.insights, generatedInsights);
  }, [generatedInsights]);


  // Persist first document modal state
  useEffect(() => {
    if (!isFirstDocument) {
      saveToStorage(STORAGE_KEYS.hasSeenFirstDocumentModal, true);
    }
  }, [isFirstDocument]);

  const addDocument = useCallback((doc: Omit<StoredDocument, 'id' | 'uploadedAt'>): StoredDocument => {
    const newDoc: StoredDocument = {
      ...doc,
      id: `doc-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      uploadedAt: new Date(),
      // Add placeholder content if not provided
      contentText: doc.contentText || `Uploaded file: ${doc.name}. Parsing pending.`,
    };
    
    setDocuments(prev => {
      const wasEmpty = prev.length === 0;
      if (wasEmpty && isFirstDocument) {
        setIsFirstDocument(false);
        setShowFirstDocumentModal(true);
      }
      return [...prev, newDoc];
    });
    
    return newDoc;
  }, [isFirstDocument]);

  const addDocuments = useCallback((docs: Omit<StoredDocument, 'id' | 'uploadedAt'>[]): StoredDocument[] => {
    const newDocs: StoredDocument[] = docs.map((doc, i) => ({
      ...doc,
      id: `doc-${Date.now()}-${i}-${Math.random().toString(36).substr(2, 9)}`,
      uploadedAt: new Date(),
      contentText: doc.contentText || `Uploaded file: ${doc.name}. Parsing pending.`,
    }));
    
    setDocuments(prev => {
      const wasEmpty = prev.length === 0;
      if (wasEmpty && isFirstDocument && newDocs.length > 0) {
        setIsFirstDocument(false);
        setShowFirstDocumentModal(true);
      }
      return [...prev, ...newDocs];
    });
    
    return newDocs;
  }, [isFirstDocument]);

  const removeDocument = useCallback((id: string) => {
    setDocuments(prev => prev.filter(doc => doc.id !== id));
  }, []);

  const addAgent = useCallback((agentData: Omit<Agent, 'id' | 'createdAt' | 'updatedAt' | 'outputCount' | 'status' | 'isPreset'>): Agent => {
    const now = new Date();
    const newAgent: Agent = {
      ...agentData,
      id: `agent-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      createdAt: now,
      updatedAt: now,
      outputCount: 0,
      status: 'active',
      isPreset: false,
    };
    
    setAgents(prev => [newAgent, ...prev]);
    
    // If agent has linked documents, simulate insight generation
    if (agentData.linkedDocumentIds.length > 0) {
      setTimeout(() => {
        generateMockInsights(newAgent);
      }, 1500);
    }
    
    return newAgent;
  }, []);

  const updateAgent = useCallback((id: string, updates: Partial<Omit<Agent, 'id' | 'createdAt' | 'isPreset'>>) => {
    setAgents(prev => prev.map(agent => {
      if (agent.id !== id) return agent;
      return {
        ...agent,
        ...updates,
        updatedAt: new Date(),
      };
    }));
  }, []);

  const deleteAgent = useCallback((id: string) => {
    setAgents(prev => {
      const agent = prev.find(a => a.id === id);
      if (agent?.isPreset) return prev;
      return prev.filter(a => a.id !== id);
    });
  }, []);

  const addInsight = useCallback((insight: Omit<Insight, 'id'>): Insight => {
    const newInsight: Insight = {
      ...insight,
      id: `insight-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    };
    setGeneratedInsights(prev => [newInsight, ...prev]);
    return newInsight;
  }, []);


  const generateMockInsights = useCallback((agent: Agent) => {
    const linkedDocs = documents.filter(d => agent.linkedDocumentIds.includes(d.id));
    const docNames = linkedDocs.map(d => d.aiTitle || d.name).join(', ');
    
    const mockInsightsToAdd: Omit<Insight, 'id'>[] = [
      {
        type: 'insight',
        title: `${agent.name} detected a pattern`,
        synthesis: `Based on analysis of ${docNames}, ${agent.name} identified emerging patterns that warrant attention. The data suggests significant trends in user behavior.`,
        source: { id: 'agent', name: agent.name, type: 'internal' },
        timestamp: new Date(),
        confidence: 0.85 + Math.random() * 0.1,
        evidenceCount: Math.floor(Math.random() * 5) + 3,
        isNew: true,
        priority: 'medium',
      },
    ];
    
    if (Math.random() > 0.4) {
      mockInsightsToAdd.push({
        type: 'pulse',
        title: `Key signal from ${linkedDocs[0]?.aiTitle || 'document'}`,
        synthesis: `Analysis reveals actionable insights from your uploaded data. Consider reviewing the highlighted patterns for strategic decision making.`,
        source: { id: 'agent', name: agent.name, type: 'internal' },
        timestamp: new Date(),
        confidence: 0.78 + Math.random() * 0.15,
        evidenceCount: Math.floor(Math.random() * 4) + 2,
        isNew: true,
        priority: 'high',
      });
    }
    
    mockInsightsToAdd.forEach(insight => addInsight(insight));
    
    setAgents(prev => prev.map(a => 
      a.id === agent.id 
        ? { ...a, outputCount: a.outputCount + mockInsightsToAdd.length, lastRun: new Date() }
        : a
    ));
  }, [documents, addInsight]);

  const openUploadModal = useCallback((source: string) => {
    setUploadModalSource(source);
    setShowUploadModal(true);
  }, []);

  // Derived values
  const customAgents = agents.filter(a => !a.isPreset);
  const presetAgents = agents.filter(a => a.isPreset);

  const value: DocumentsContextType = {
    documents,
    addDocument,
    addDocuments,
    removeDocument,
    hasDocuments: documents.length > 0,
    agents,
    addAgent,
    updateAgent,
    deleteAgent,
    hasAgents: agents.length > 0,
    customAgents,
    presetAgents,
    generatedInsights,
    addInsight,
    showFirstDocumentModal,
    setShowFirstDocumentModal,
    isFirstDocument,
    showUploadModal,
    setShowUploadModal,
    uploadModalSource,
    openUploadModal,
  };

  return (
    <DocumentsContext.Provider value={value}>
      {children}
    </DocumentsContext.Provider>
  );
}

export function useDocuments() {
  const context = useContext(DocumentsContext);
  if (context === undefined) {
    throw new Error('useDocuments must be used within a DocumentsProvider');
  }
  return context;
}
