import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';
import { Insight, Agent } from '@/types';

// Document type stored in context
export interface StoredDocument {
  id: string;
  name: string;
  type: string;
  source: 'upload' | 'connected';
  uploadedAt: Date;
  aiTitle?: string;
}

// Extended Agent type with linked documents
export interface CreatedAgent extends Omit<Agent, 'type'> {
  type: Agent['type'] | 'custom';
  prompt: string;
  frequency: string;
  linkedDocumentIds: string[];
  createdAt: Date;
}

interface DocumentsContextType {
  // Documents
  documents: StoredDocument[];
  addDocument: (doc: Omit<StoredDocument, 'id' | 'uploadedAt'>) => StoredDocument;
  addDocuments: (docs: Omit<StoredDocument, 'id' | 'uploadedAt'>[]) => StoredDocument[];
  removeDocument: (id: string) => void;
  hasDocuments: boolean;
  
  // Agents
  agents: CreatedAgent[];
  addAgent: (agent: Omit<CreatedAgent, 'id' | 'createdAt' | 'outputCount' | 'status'>) => CreatedAgent;
  hasAgents: boolean;
  
  // Insights (generated by agents)
  generatedInsights: Insight[];
  addInsight: (insight: Omit<Insight, 'id'>) => Insight;
  
  // First-time user flow
  showFirstDocumentModal: boolean;
  setShowFirstDocumentModal: (show: boolean) => void;
  isFirstDocument: boolean;
  
  // Upload modal control
  showUploadModal: boolean;
  setShowUploadModal: (show: boolean) => void;
  uploadModalSource: string;
  openUploadModal: (source: string) => void;
}

const DocumentsContext = createContext<DocumentsContextType | undefined>(undefined);

export function DocumentsProvider({ children }: { children: ReactNode }) {
  const [documents, setDocuments] = useState<StoredDocument[]>([]);
  const [agents, setAgents] = useState<CreatedAgent[]>([]);
  const [generatedInsights, setGeneratedInsights] = useState<Insight[]>([]);
  const [showFirstDocumentModal, setShowFirstDocumentModal] = useState(false);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [uploadModalSource, setUploadModalSource] = useState('');
  const [isFirstDocument, setIsFirstDocument] = useState(true);

  const addDocument = useCallback((doc: Omit<StoredDocument, 'id' | 'uploadedAt'>): StoredDocument => {
    const newDoc: StoredDocument = {
      ...doc,
      id: `doc-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      uploadedAt: new Date(),
    };
    
    setDocuments(prev => {
      const wasEmpty = prev.length === 0;
      if (wasEmpty && isFirstDocument) {
        setIsFirstDocument(false);
        setShowFirstDocumentModal(true);
      }
      return [...prev, newDoc];
    });
    
    return newDoc;
  }, [isFirstDocument]);

  const addDocuments = useCallback((docs: Omit<StoredDocument, 'id' | 'uploadedAt'>[]): StoredDocument[] => {
    const newDocs: StoredDocument[] = docs.map((doc, i) => ({
      ...doc,
      id: `doc-${Date.now()}-${i}-${Math.random().toString(36).substr(2, 9)}`,
      uploadedAt: new Date(),
    }));
    
    setDocuments(prev => {
      const wasEmpty = prev.length === 0;
      if (wasEmpty && isFirstDocument && newDocs.length > 0) {
        setIsFirstDocument(false);
        setShowFirstDocumentModal(true);
      }
      return [...prev, ...newDocs];
    });
    
    return newDocs;
  }, [isFirstDocument]);

  const removeDocument = useCallback((id: string) => {
    setDocuments(prev => prev.filter(doc => doc.id !== id));
  }, []);

  const addAgent = useCallback((agent: Omit<CreatedAgent, 'id' | 'createdAt' | 'outputCount' | 'status'>): CreatedAgent => {
    const newAgent: CreatedAgent = {
      ...agent,
      id: `agent-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      createdAt: new Date(),
      outputCount: 0,
      status: 'active',
    };
    
    setAgents(prev => [...prev, newAgent]);
    
    // If agent has linked documents, simulate insight generation
    if (agent.linkedDocumentIds.length > 0) {
      setTimeout(() => {
        generateMockInsights(newAgent);
      }, 1500); // Simulate processing delay
    }
    
    return newAgent;
  }, []);

  const addInsight = useCallback((insight: Omit<Insight, 'id'>): Insight => {
    const newInsight: Insight = {
      ...insight,
      id: `insight-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    };
    setGeneratedInsights(prev => [newInsight, ...prev]);
    return newInsight;
  }, []);

  const generateMockInsights = useCallback((agent: CreatedAgent) => {
    const linkedDocs = documents.filter(d => agent.linkedDocumentIds.includes(d.id));
    const docNames = linkedDocs.map(d => d.aiTitle || d.name).join(', ');
    
    // Generate 1-2 mock insights based on the agent
    const mockInsights: Omit<Insight, 'id'>[] = [
      {
        type: 'insight',
        title: `${agent.name} detected a pattern`,
        synthesis: `Based on analysis of ${docNames}, ${agent.name} identified emerging patterns that warrant attention. The data suggests significant trends in user behavior.`,
        source: { id: 'agent', name: agent.name, type: 'internal' },
        timestamp: new Date(),
        confidence: 0.85 + Math.random() * 0.1,
        evidenceCount: Math.floor(Math.random() * 5) + 3,
        isNew: true,
        priority: 'medium',
      },
    ];
    
    // Sometimes generate a second insight
    if (Math.random() > 0.4) {
      mockInsights.push({
        type: 'pulse',
        title: `Key signal from ${linkedDocs[0]?.aiTitle || 'document'}`,
        synthesis: `Analysis reveals actionable insights from your uploaded data. Consider reviewing the highlighted patterns for strategic decision making.`,
        source: { id: 'agent', name: agent.name, type: 'internal' },
        timestamp: new Date(),
        confidence: 0.78 + Math.random() * 0.15,
        evidenceCount: Math.floor(Math.random() * 4) + 2,
        isNew: true,
        priority: 'high',
      });
    }
    
    mockInsights.forEach(insight => addInsight(insight));
    
    // Update agent output count
    setAgents(prev => prev.map(a => 
      a.id === agent.id 
        ? { ...a, outputCount: a.outputCount + mockInsights.length, lastRun: new Date() }
        : a
    ));
  }, [documents, addInsight]);

  const openUploadModal = useCallback((source: string) => {
    setUploadModalSource(source);
    setShowUploadModal(true);
  }, []);

  const value: DocumentsContextType = {
    documents,
    addDocument,
    addDocuments,
    removeDocument,
    hasDocuments: documents.length > 0,
    agents,
    addAgent,
    hasAgents: agents.length > 0,
    generatedInsights,
    addInsight,
    showFirstDocumentModal,
    setShowFirstDocumentModal,
    isFirstDocument,
    showUploadModal,
    setShowUploadModal,
    uploadModalSource,
    openUploadModal,
  };

  return (
    <DocumentsContext.Provider value={value}>
      {children}
    </DocumentsContext.Provider>
  );
}

export function useDocuments() {
  const context = useContext(DocumentsContext);
  if (context === undefined) {
    throw new Error('useDocuments must be used within a DocumentsProvider');
  }
  return context;
}
