import { motion, AnimatePresence } from 'framer-motion';
import { X, FileText, Bot, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { StoredDocument } from '@/contexts/DocumentsContext';
import { AskEvidenceCard } from '@/types/ask';
import { getDocumentIcon, getSourceTypeLabel } from '@/utils/documentSynthesis';

interface EvidenceDetailPanelProps {
  evidence: AskEvidenceCard;
  sourceDocuments: StoredDocument[];
  onClose: () => void;
}

export function EvidenceDetailPanel({
  evidence,
  sourceDocuments,
  onClose,
}: EvidenceDetailPanelProps) {
  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-start justify-end bg-background/60 backdrop-blur-sm"
        onClick={onClose}
      >
        <motion.div
          initial={{ x: '100%' }}
          animate={{ x: 0 }}
          exit={{ x: '100%' }}
          transition={{ type: 'spring', damping: 30, stiffness: 300 }}
          className="h-full w-full max-w-lg bg-card border-l border-border shadow-xl overflow-y-auto"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="sticky top-0 z-10 bg-card border-b border-border px-6 py-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span
                className={`px-2.5 py-1 rounded-md text-xs font-medium ${
                  evidence.type === 'quantitative'
                    ? 'bg-primary/10 text-primary'
                    : 'bg-secondary/10 text-secondary'
                }`}
              >
                {evidence.type}
              </span>
            </div>
            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-muted transition-colors text-muted-foreground hover:text-foreground"
            >
              <X className="w-5 h-5" strokeWidth={1.5} />
            </button>
          </div>

          <div className="p-6 space-y-8">
            {/* Evidence Title */}
            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                {evidence.label}
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                {evidence.explanation}
              </p>
            </div>

            {/* Agent Attribution */}
            {evidence.agentName && (
              <div className="bg-muted/50 rounded-xl p-4 flex items-center gap-3">
                <div className="w-9 h-9 rounded-lg bg-muted flex items-center justify-center">
                  <Bot className="w-4 h-4 text-muted-foreground" strokeWidth={1.5} />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Generated by</p>
                  <p className="font-medium text-foreground">{evidence.agentName}</p>
                </div>
              </div>
            )}

            {/* Source Documents */}
            <div>
              <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-3">
                Source documents ({sourceDocuments.length})
              </h3>
              {sourceDocuments.length > 0 ? (
                <div className="space-y-2">
                  {sourceDocuments.map((doc) => (
                    <div
                      key={doc.id}
                      className="bg-card rounded-xl p-4 border border-border flex items-center justify-between group hover:bg-muted/50 transition-colors cursor-pointer"
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <span className="text-base flex-shrink-0">
                          {getDocumentIcon(doc)}
                        </span>
                        <div className="min-w-0">
                          <p className="font-medium text-foreground truncate">
                            {doc.aiTitle || doc.name}
                          </p>
                          <p className="text-sm text-muted-foreground">
                            {getSourceTypeLabel(doc)}
                          </p>
                        </div>
                      </div>
                      <ExternalLink className="w-4 h-4 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity" />
                    </div>
                  ))}
                </div>
              ) : (
                <div className="bg-muted/50 rounded-xl p-4 text-center">
                  <p className="text-muted-foreground text-sm">
                    Source documents are not available
                  </p>
                </div>
              )}
            </div>

            {/* Relevant Excerpt Placeholder */}
            <div>
              <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-3">
                Relevant excerpt
              </h3>
              <div className="bg-muted/30 rounded-xl p-5 border-l-4 border-primary/30">
                <p className="text-foreground italic">
                  "Evidence excerpt from source documents would appear here, highlighting the specific data points or quotes that support this finding."
                </p>
                <p className="text-sm text-muted-foreground mt-3">
                  — From {sourceDocuments[0]?.aiTitle || 'uploaded document'}
                </p>
              </div>
            </div>

            {/* Actions */}
            <div className="flex flex-wrap gap-3 pt-4 border-t border-border">
              <Button variant="outline" className="rounded-xl">
                <ExternalLink className="w-4 h-4 mr-2" strokeWidth={1.5} />
                Open document
              </Button>
              <Button variant="outline" className="rounded-xl">
                <FileText className="w-4 h-4 mr-2" strokeWidth={1.5} />
                View all excerpts
              </Button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
