import { motion } from 'framer-motion';
import { ArrowLeft, CircleDot, FileText, MessageSquare, Target, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useDocuments } from '@/contexts/DocumentsContext';

interface InsightDetailViewProps {
  onClose: () => void;
  insight: {
    headline: string;
    type: 'Signal' | 'Insight';
    source: string;
    contributorCount: number;
  };
}

export function InsightDetailView({ onClose, insight }: InsightDetailViewProps) {
  const { documents, agents } = useDocuments();
  
  // Generate context-aware expanded data based on real documents
  const hasDocuments = documents.length > 0;
  const activeAgents = agents.filter(a => a.isActive);
  
  const expandedData = {
    whatChanged: hasDocuments
      ? `Based on analysis of ${documents.length} uploaded document${documents.length !== 1 ? 's' : ''}, patterns have emerged that indicate significant user behavior changes. The data reveals trends that warrant attention and potential action.`
      : "Analysis reveals patterns in user behavior that warrant attention.",
    whyItMatters: hasDocuments
      ? "Understanding these patterns from your data helps inform strategic decisions and prioritize product improvements that will have the greatest impact."
      : "This insight helps inform strategic decisions and product improvements.",
    likelyCause: hasDocuments
      ? "The patterns identified suggest opportunities for improvement in key user journey stages, based on synthesis of qualitative and quantitative signals from your sources."
      : "Further investigation may reveal specific causes and opportunities.",
    confidence: insight.contributorCount > 5 ? 87 : insight.contributorCount > 2 ? 72 : 58,
    timeWindow: "Recent analysis",
    generatedBy: activeAgents.length > 0 ? activeAgents[0].name : "Insight Synthesizer",
    documents: documents.length,
    sourceTypes: documents.length > 0
      ? [...new Set(documents.slice(0, 3).map(d => insight.source))]
      : [insight.source]
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 20 }}
      className="min-h-full"
    >
      {/* Header */}
      <div className="flex items-center gap-3 mb-8">
        <button
          onClick={onClose}
          className="p-2 hover:bg-muted rounded-xl transition-colors"
        >
          <ArrowLeft className="w-4 h-4 text-muted-foreground" strokeWidth={3} />
        </button>
        <div className="flex items-center gap-2">
          <span className={`px-2.5 py-1 rounded-md text-xs font-medium ${
            insight.type === 'Signal' 
              ? 'bg-orange-100 text-orange-700' 
              : 'bg-blue-100 text-blue-700'
          }`}>
            {insight.type}
          </span>
        </div>
      </div>

      {/* Headline */}
      <h1 className="text-2xl font-semibold text-foreground mb-8">
        {insight.headline}
      </h1>

      {/* Expanded Explanation */}
      <div className="space-y-6 mb-10">
        <div className="bg-card rounded-2xl p-5 shadow-card border border-border/50">
          <h3 className="text-sm font-medium text-muted-foreground mb-2">What changed</h3>
          <p className="text-foreground">{expandedData.whatChanged}</p>
        </div>

        <div className="bg-card rounded-2xl p-5 shadow-card border border-border/50">
          <h3 className="text-sm font-medium text-muted-foreground mb-2">Why it matters</h3>
          <p className="text-foreground">{expandedData.whyItMatters}</p>
        </div>

        <div className="bg-card rounded-2xl p-5 shadow-card border border-border/50">
          <h3 className="text-sm font-medium text-muted-foreground mb-2">What's likely causing it</h3>
          <p className="text-foreground">{expandedData.likelyCause}</p>
        </div>
      </div>

      {/* Metadata */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4 mb-10">
        <div className="bg-muted/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Confidence</p>
          <p className="text-lg font-semibold text-foreground">{expandedData.confidence}%</p>
        </div>
        <div className="bg-muted/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Time window</p>
          <p className="text-lg font-semibold text-foreground">{expandedData.timeWindow}</p>
        </div>
        <div className="bg-muted/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Generated by</p>
          <p className="text-lg font-semibold text-foreground">{expandedData.generatedBy}</p>
        </div>
        <div className="bg-muted/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Documents analyzed</p>
          <p className="text-lg font-semibold text-foreground">{expandedData.documents}</p>
        </div>
      </div>

      {/* Source Summary */}
      <div className="bg-card rounded-2xl p-5 shadow-card border border-border/50 mb-10">
        <h3 className="text-sm font-medium text-muted-foreground mb-3">Top source types</h3>
        <div className="flex flex-wrap gap-2">
          {expandedData.sourceTypes.map((type) => (
            <span key={type} className="px-3 py-1.5 bg-muted rounded-full text-sm font-medium text-foreground">
              {type}
            </span>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-3">
        <Button variant="outline" className="rounded-xl">
          <MessageSquare className="w-4 h-4 mr-2" strokeWidth={3} />
          Ask follow-up question
        </Button>
        <Button variant="outline" className="rounded-xl">
          <FileText className="w-4 h-4 mr-2" strokeWidth={3} />
          View supporting sources
        </Button>
        <Button variant="outline" className="rounded-xl">
          <Target className="w-4 h-4 mr-2" strokeWidth={3} />
          Link to a goal
        </Button>
      </div>
    </motion.div>
  );
}
