import { motion } from 'framer-motion';
import { ArrowLeft, CircleDot, FileText, MessageSquare, Target, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface InsightDetailViewProps {
  onClose: () => void;
  insight: {
    headline: string;
    type: 'Signal' | 'Insight';
    source: string;
    contributorCount: number;
  };
}

export function InsightDetailView({ onClose, insight }: InsightDetailViewProps) {
  // Mock expanded data
  const expandedData = {
    whatChanged: "User retention dropped 23% over the past 30 days, with the sharpest decline occurring in the second week of the user lifecycle. This coincides with the workspace setup step where completion rates fell from 67% to 44%.",
    whyItMatters: "Early lifecycle drop-off directly impacts lifetime value and increases customer acquisition cost pressure. Users who don't complete workspace setup within the first week have a 78% lower chance of becoming paid customers.",
    likelyCause: "The multi-step workspace configuration requires users to make decisions about permissions and team structure before experiencing core product value. This creates friction at the moment of highest intent.",
    confidence: 87,
    timeWindow: "Last 30 days",
    generatedBy: "Adoption Tracker",
    documents: 12,
    sourceTypes: ['User interviews', 'Product analytics', 'Support tickets']
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 20 }}
      className="min-h-full"
    >
      {/* Header */}
      <div className="flex items-center gap-3 mb-8">
        <button
          onClick={onClose}
          className="p-2 hover:bg-muted rounded-xl transition-colors"
        >
          <ArrowLeft className="w-5 h-5 text-muted-foreground" />
        </button>
        <div className="flex items-center gap-2">
          <span className={`px-2.5 py-1 rounded-md text-xs font-medium ${
            insight.type === 'Signal' 
              ? 'bg-orange-100 text-orange-700' 
              : 'bg-blue-100 text-blue-700'
          }`}>
            {insight.type}
          </span>
        </div>
      </div>

      {/* Headline */}
      <h1 className="text-2xl font-semibold text-foreground mb-8">
        {insight.headline}
      </h1>

      {/* Expanded Explanation */}
      <div className="space-y-6 mb-10">
        <div className="bg-card rounded-2xl p-5 shadow-card border border-border/50">
          <h3 className="text-sm font-medium text-muted-foreground mb-2">What changed</h3>
          <p className="text-foreground">{expandedData.whatChanged}</p>
        </div>

        <div className="bg-card rounded-2xl p-5 shadow-card border border-border/50">
          <h3 className="text-sm font-medium text-muted-foreground mb-2">Why it matters</h3>
          <p className="text-foreground">{expandedData.whyItMatters}</p>
        </div>

        <div className="bg-card rounded-2xl p-5 shadow-card border border-border/50">
          <h3 className="text-sm font-medium text-muted-foreground mb-2">What's likely causing it</h3>
          <p className="text-foreground">{expandedData.likelyCause}</p>
        </div>
      </div>

      {/* Metadata */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4 mb-10">
        <div className="bg-muted/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Confidence</p>
          <p className="text-lg font-semibold text-foreground">{expandedData.confidence}%</p>
        </div>
        <div className="bg-muted/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Time window</p>
          <p className="text-lg font-semibold text-foreground">{expandedData.timeWindow}</p>
        </div>
        <div className="bg-muted/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Generated by</p>
          <p className="text-lg font-semibold text-foreground">{expandedData.generatedBy}</p>
        </div>
        <div className="bg-muted/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Documents analyzed</p>
          <p className="text-lg font-semibold text-foreground">{expandedData.documents}</p>
        </div>
      </div>

      {/* Source Summary */}
      <div className="bg-card rounded-2xl p-5 shadow-card border border-border/50 mb-10">
        <h3 className="text-sm font-medium text-muted-foreground mb-3">Top source types</h3>
        <div className="flex flex-wrap gap-2">
          {expandedData.sourceTypes.map((type) => (
            <span key={type} className="px-3 py-1.5 bg-muted rounded-full text-sm font-medium text-foreground">
              {type}
            </span>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-3">
        <Button variant="outline" className="rounded-xl">
          <MessageSquare className="w-4 h-4 mr-2" />
          Ask follow-up question
        </Button>
        <Button variant="outline" className="rounded-xl">
          <FileText className="w-4 h-4 mr-2" />
          View supporting sources
        </Button>
        <Button variant="outline" className="rounded-xl">
          <Target className="w-4 h-4 mr-2" />
          Link to a goal
        </Button>
      </div>
    </motion.div>
  );
}
