// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijqgseqbvnchsbzfxkza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqcWdzZXFidm5jaHNiemZ4a3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyOTM3NTYsImV4cCI6MjA4NTg2OTc1Nn0.vYNl7cZfPIHI_qnxL7XcMEZMErF3j3FS9TyN2Jpj080";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});